### ISSUE TITLE
In Manage Departments Three Levels do not show

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#40] opened 2022-05-04 16:15 UTC
When you are looking at the manage departments screen in WebApps you can only see 2 levels of departments in the list. 

Example
Estates - Facilities - Cleaning
shows up as

Estates
Facilieis - Cleaning

Is this by design or should it show the full level list?

**Comment by RobTrehy** [comment] 2022-05-06 09:41
Duplicate of #24

**Closed by RobTrehy** 2022-05-06 09:41 UTC
Labels: duplicate
